[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[override]]
  branch = "master"
  name = "github.com/blk-io/chimera"

[prune]
  go-tests = true